AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/LineLength:
  # The default, 80, is a nice-to-have but not really all that relevant
  # on today's wide screens. Use 120 as a "hard" cap and try to be shorter.
  Max: 120

Metrics/MethodLength:
  # The default, 10, seems silly here.
  Max: 25

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/EmptyElse:
  # I'd rather have empty else branches than forget one.
  Enabled: false