on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-pdflatex:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby:
         - '3.1'
         - '3.2'
         - '3.3'
    name: "${{ matrix.os }} / ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: Setup dependencies
        run: |
          bundle update --bundler
          bundle install

      - name: Install TeX Live
        if: matrix.os != 'windows-latest'
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            latex-bin scheme-basic

      - name: Install MiKTeX
        if: matrix.os == 'windows-latest'
        run: |
          choco install miktex --no-progress
          echo "C:\Program Files\MiKTeX\miktex\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Configure MiKTeX
        if: matrix.os == 'windows-latest'
        run: |
          initexmf --admin --set-config-value=[MPM]AutoInstall=1
          miktex --admin packages update-package-database
          miktex --admin packages update
          miktex packages update
          miktex --admin packages install cm-super
          miktex --admin fndb refresh
          initexmf --admin --update-fndb
          initexmf --admin --mklinks --force
          updmap --admin
          initexmf --report > miktex-report.txt

      - name: ltx2any
        run: |
          ruby ltx2any.rb test/test.tex
